{
 "title": "Solar Assistant - Production Central",
 "tags": [
  "solar-assistant",
  "production",
  "home-assistant"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "power_measurement", "label": "Power measurement", "query": "W,state" }
  ]
 },
 "panels": [
  {
   "title": "Current inverter production",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"last\") FROM (SELECT last(\"value\") AS \"last\" FROM \"$power_measurement\" WHERE \"entity_id\" =~ /^inverter_.*_power$/ AND $timeFilter GROUP BY \"entity_id\")"
    }
   ]
  },
  {
   "title": "Panel inverter production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_entity_id",
     "query": "SELECT mean(\"value\") FROM \"$power_measurement\" WHERE \"entity_id\" =~ /^inverter_.*_power$/ AND $timeFilter GROUP BY time($__interval), \"entity_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Current output by panel",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_entity_id",
     "query": "SELECT last(\"value\") FROM \"$power_measurement\" WHERE \"entity_id\" =~ /^inverter_.*_power$/ AND $timeFilter GROUP BY \"entity_id\""
    }
   ]
  },
  {
   "title": "Grid and home power meter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_entity_id",
     "query": "SELECT mean(\"value\") FROM \"$power_measurement\" WHERE \"entity_id\" =~ /^power_meter_pvs6.*power$/ AND $timeFilter GROUP BY time($__interval), \"entity_id\" fill(null)"
    }
   ]
  }
 ]
}